spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${EMPLOYEE_DB_NAME:employee}
    username: ${MYSQL_DB_USERNAME:root}
    password: ${MYSQL_DB_PASSWORD:generic}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
